#! /bin/zsh


# █▀█ █▀█ █▀█ █▀▄▀█ █▀█ ▀█▀
# █▀▀ █▀▄ █▄█ █░▀░█ █▀▀ ░█░

PS1="%F{green}──(%f%B%F{magenta}%n%f%b%F{green}@%f%B%F{magenta}%m%f%b%F{green})──(%B%F{yellow}%~%f%b%F{green}) $%f "


# █▀▀ █▀█ █░░ █▀█ █▀█
# █▄▄ █▄█ █▄▄ █▄█ █▀▄

# Man
LESS_TERMCAP_mb=$'\e[1;35m'
LESS_TERMCAP_md=$'\e[1;35m'
LESS_TERMCAP_me=$'\e[0m'
LESS_TERMCAP_se=$'\e[0m'
LESS_TERMCAP_so=$'\e[1;35m'
LESS_TERMCAP_ue=$'\e[0m'
LESS_TERMCAP_us=$'\e[1;33m'


# █▀▀ ▀█ █▀▀
# █▀░ █▄ █▀░

# Adding royal theme to fzf
export FZF_DEFAULT_OPTS=" \
--color=bg+:#3f3f3c,bg:#282a2e,spinner:#63d1ab,hl:#63d1ab \
--color=fg:#dfce9d,header:#dfce9d,info:#9a8a5c,pointer:#9a8a5c \
--color=marker:#dfce9d,fg+:#d19d63,prompt:#9a8a5c,hl+:#63d1ab"
